# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    format_listener: true
    view:
        view_response_listener: "force"
        formats:
            txt: true
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
    service:
        inflector: api_bundle.noop_inflector
