<?php

namespace App\ApiBundle\Repository;

/**
 * ExampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleRepository extends \Doctrine\ORM\EntityRepository
{
}
